config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  get 'weekly_report/' => 'time_and_attendance_reports#users'
  get 'punchlog/' => 'time_and_attendance_reports#punchlog'
  get 'report/week' => 'time_and_attendance_reports#weekly_report'
  post 'update/staff' => 'time_and_attendance_reports#update_staff'
  get 'send/email' => 'time_and_attendance_reports#send_weekly_report'
  get 'report/new_staff' => 'time_and_attendance_reports#add_user_to_report'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/punchlog.rb
class Punchlog < ApplicationRecord
  self.table_name = 'punchlog'

  def self.send_mail
    WeeklyReportMailer.weekly_report_email.deliver_now
  end
end

app/models/uguser.rb
class Uguser < ApplicationRecord
  self.table_name = 'uguser'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/time_and_attendance_reports_controller.rb
class TimeAndAttendanceReportsController < ApplicationController
  @@devices = {
    login: {
      id: 546838262,
      name: 'BioStation 2 546838262 (172.18.1.41)'
    },
    logout: {
      id: 541614750,
      name: 'Main Entrance slave P2 541614750'
    },
    other: {
      id: 545391539,
      name: 'SUITE 3 545391539 (172.18.1.85)'
    }
  }

  def users
    current_month = Date.today.month
    current_day = Date.today - 1.week
    @current_work_week = current_day.beginning_of_week..(current_day.end_of_week)
    staff_list = Uguser.where.not(staff_name: nil)
    @punchlog = []
    staff_list.each do |staff|
      @punchlog.push(
        Punchlog.where(bsevtdt: @current_work_week, user_id: staff.user_id).select(:devid, :devnm, :user_name, :user_id, :bsevtdt)
      )
    end
    respond_to do |format|
      format.html
      format.xlsx
    end
  end

  def add_user_to_report
    current_month = Date.today.month
    current_day = Date.today  - 1.week
    @current_work_week = current_day.beginning_of_week..(current_day.end_of_week)
    staff_list = Uguser.where(staff_name: nil)
    @punchlog = []
    staff_list.each do |staff|
      @punchlog.push(
        Punchlog.where(bsevtdt: @current_work_week, user_id: staff.user_id).select(:devid, :devnm, :user_name, :user_id, :bsevtdt)
      )
    end
    respond_to do |format|
      format.html
    end
  end

  def update_staff
    staff = Uguser.find_by_user_id(params[:user_id])
    staff.staff_name = params[:staff_name]
    if staff.save!
      respond_to do |format|
        format.js {render inline: "location.reload();" }
      end
    end
  end

  def send_weekly_report
    WeeklyReportMailer.weekly_report_email.deliver_now
  end

  def punchlog
    punchlog = Punchlog.all.select(:devid, :devnm, :user_name, :user_id, :bsevtdt)
    render json: punchlog
  end

  private

  def update_user_params
    params.permit(:user_id, :staff_name)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/time_and_attendance_reports_helper.rb
module TimeAndAttendanceReportsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BiostarReportAutomationEmail</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body>
    <nav class="items-center justify-between flex-wrap bg-teal-500 p-6">
      <div class="w-full block flex-grow lg:flex lg:items-center lg:w-auto">
        <div class="text-sm lg:flex-grow">
          <a class="block mt-4 lg:inline-block lg:mt-0 text-teal-200 hover:text-white mr-4" href="/weekly_report">Weekly Report</a>
          <a class="block mt-4 lg:inline-block lg:mt-0 text-teal-200 hover:text-white mr-4" href="/weekly_report.xlsx">Download Report</a>
          <a class="block mt-4 lg:inline-block lg:mt-0 text-teal-200 hover:text-white mr-4" href="/report/new_staff">Add User to Report</a>
        </div>
      </div>
    </nav>
    <main class="container mx-auto mt-28 px-5 flex">
      <div class="container">
        <%= yield %>
      </div>
    </main>
  </body>
</html>

app/views/time_and_attendance_reports/add_user_to_report.html.erb
<%
devices = {
  login: {
    id: 546838262,
    name: 'Leonardo In'
  },
  logout: {
    id: 541614750,
    name: 'Leonardo Out'
  }
}
 %>
<h1 class="mb-4 text-4xl font-extrabold leading-none tracking-tight text-gray-900 md:text-5xl lg:text-6xl">Add Employee to Report</h1>
<div class="">
  <table class="w-full text-sm text-left text-gray-500 dark:text-gray-400">
    <thead class="text-xs text-gray-700 uppercase bg-gray-50 dark:bg-gray-700 dark:text-gray-400">
      <th scope="col" class="px-6 py-3">Date</th>
      <th scope="col" class="px-6 py-3">Name</th>
      <th scope="col" class="px-6 py-3">Log In Time</th>
      <th scope="col" class="px-6 py-3">Log Out Time</th>
      <th scope="col" class="px-6 py-3">Time in Office (Minutes)</th>
      <th scope="col" class="px-6 py-3">Device</th>
      <th scope="col" class="px-6 py-3">DeviceName</th>
    </thead>
    <tbody>
      <% total_employee_hours = 0 %>
      <% @punchlog.each do |staff_logs| %>
        <% n = 0 %>
        <% total_hours = 0 %>
        <% staff_logs.each do |log| %>
          <tr class="bg-white border-b dark:bg-gray-800 dark:border-gray-700 hover:bg-gray-50 dark:hover:bg-gray-600">
            <td><%= log.bsevtdt.strftime("%A") %></td>
            <td><%= Uguser.find_by_user_id(log.user_id).staff_name %></td>
            <td>
              <% if log.devid.to_s ==  devices[:login][:id].to_s %>
                <%= log.bsevtdt %>
              <% end %>
            </td>
            <td>
              <% if log.devid.to_s ==  devices[:logout][:id].to_s %>
                <%= log.bsevtdt %>
              <% end %>
            </td>
            <td>
              <% if log.devid.to_s ==  devices[:logout][:id].to_s %>
                <%= Time.at(log.bsevtdt - staff_logs.limit(1).offset(n - 1).first.bsevtdt).utc.strftime("%H:%M") %>
              <% end %>
            </td>
            <td><%= log.devid %></td>
            <td><%= log.devnm %></td>
          </tr>
          <% if log.devid.to_s ==  devices[:logout][:id].to_s %>
            <% total_hours += ((log.bsevtdt - staff_logs.limit(1).offset(n - 1).first.bsevtdt) / 60) / 60 %>
          <% end %>
          <% n += 1 %>
        <% end %>
          <% if staff_logs.any? %>
            <tr class="font-semibold text-gray-900">
              <td>Total Hours for</td>
              <td><%= Uguser.find_by_user_id(staff_logs.first.user_id).staff_name %></td>
              <td></td>
              <td></td>
              <td>
                <%= total_hours.to_i %>:<%= ((total_hours * 60) % 60).to_i %>
                <% total_employee_hours += total_hours %>
              </td>
              <td>
                <%= form_with url: "/update/staff", method: :post do |form| %>
                  <%= form.hidden_field :user_id, value: staff_logs.first.user_id %>
                  <div class="grid md:grid-cols-2 md:gap-6">
                    <div class="relative z-0 w-full mb-6 grou">
                      <%= form.text_field :staff_name, placeholder: 'Enter Staff Name', class: 'text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5' %>
                    </div>
                    <div class="relative z-0 w-full mb-6 grou">
                      <button type="button" class="text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 mr-2 mb-2 dark:bg-blue-600 dark:hover:bg-blue-700 focus:outline-none dark:focus:ring-blue-800"><%= form.submit "Add Employee" %></button>
                    </div>
                  </div>
                <% end %>
              </td>
            </tr>
          <% end %>
      <% end %>
      <tr>
        <td>Total Hours All Employees</td>
        <td></td>
        <td></td>
        <td></td>
        <td>
          <%= total_employee_hours.to_i %>:<%= ((total_employee_hours * 60) % 60).to_i %>
        </td>
      </tr>
    </tbody>
  </table>

</div>

app/views/time_and_attendance_reports/users.html.erb
<%
devices = {
  login: {
    id: 546838262,
    name: 'Leonardo In'
  },
  logout: {
    id: 541614750,
    name: 'Leonardo Out'
  }
}
 %>
<h1>Weekly Report <%= @current_work_week %></h1><a href="/weekly_report.xlsx">Download Report</a>
<table class="table striped">
  <thead>
    <th>Date</th>
    <th>Name</th>
    <th>Log In Time</th>
    <th>Log Out Time</th>
    <th>Time in Office (Minutes)</th>
    <th>Device</th>
    <th>DeviceName</th>
  </thead>
  <tbody>
    <% total_employee_hours = 0 %>
    <% @punchlog.each do |staff_logs| %>
      <% n = 0 %>
      <% total_hours = 0 %>
      <% staff_logs.each do |log| %>
        <tr>
          <td><%= log.bsevtdt.strftime("%A") %></td>
          <td><%= Uguser.find_by_user_id(log.user_id).staff_name %></td>
          <td>
            <% if log.devid.to_s ==  devices[:login][:id].to_s %>
              <%= log.bsevtdt %>
            <% end %>
          </td>
          <td>
            <% if log.devid.to_s ==  devices[:logout][:id].to_s %>
              <%= log.bsevtdt %>
            <% end %>
          </td>
          <td>
            <% if log.devid.to_s ==  devices[:logout][:id].to_s %>
              <% if (n - 1) >= 0 %>
                <%= Time.at(log.bsevtdt - staff_logs.limit(1).offset(n - 1).first.bsevtdt).utc.strftime("%H:%M") %>
              <% end %>
            <% end %>
          </td>
          <td><%= log.devid %></td>
          <td><%= log.devnm %></td>
        </tr>
        <% if log.devid.to_s ==  devices[:logout][:id].to_s %>
          <% if (n - 1) >= 0 %>
            <% total_hours += ((log.bsevtdt - staff_logs.limit(1).offset(n - 1).first.bsevtdt) / 60) / 60 %>
          <% end %>
        <% end %>
        <% n += 1 %>
      <% end %>
        <% if staff_logs.any? %>
          <tr>
            <td>Total Hours for</td>
            <td><%= Uguser.find_by_user_id(staff_logs.first.user_id).staff_name %></td>
            <td></td>
            <td></td>
            <td>
              <%= total_hours.to_i %>:<%= ((total_hours * 60) % 60).to_i %>
              <% total_employee_hours += total_hours %>
            </td>
          </tr>
        <% end %>
    <% end %>
    <tr>
      <td>Total Hours All Employees</td>
      <td></td>
      <td></td>
      <td></td>
      <td>
        <%= total_employee_hours.to_i %>:<%= ((total_employee_hours * 60) % 60).to_i %>
      </td>
    </tr>
  </tbody>
</table>

app/views/time_and_attendance_reports/weekly_report.html.erb
<h1>Weekly Report <%= @weekly_attendance[:current_work_week] %> </h1><%= link_to "Export report as spreadsheet", report_week_path(format: "xlsx") %>
<table class="table striped">
  <thead>
    <th>Date</th>
    <th>Name</th>
    <th>Log In Time</th>
    <th>Log Out Time</th>
    <th>Total Employee Hours</th>
    <th>Device</th>
    <th>DeviceName</th>
  </thead>
  <tbody>
    <% @weekly_attendance[:punchlog].each do |log| %>
      <tr>
          <td><%= log[:Date] %></td>
          <td><%= log[:Name] %></td>
          <td><%= log[:LogInTime] %></td>
          <td><%= log[:LogOutTime] %></td>
          <td><%= log[:TimeInOffice] %></td>
          <td><%= log[:Device] %></td>
          <td><%= log[:DeviceName] %></td>
      </tr>
    <% end %>
  </tbody>
</table>